# Generated by Django 2.2.2 on 2019-10-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(help_text='in months')),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Basic Course', 'Basic Course'), ('Accounting Course', 'Accounting Course'), ('Designing Course', 'Designing Course'), ('Spoken English', 'Spoken English'), ('Digital Marketing', 'Digital Marketing'), ('IT Professional', 'IT Professional')], default='Basic Course', max_length=50)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
