# Generated by Django 2.2.2 on 2019-10-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cciApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
